### ISSUE TITLE
Unable to run nginx on GKE v1.22+

### ISSUE THREAD

**Issue by akranga** [agilestacks/google-components#2]
Trying to install nginx component on GKE version v1.22+. Pod fails with the following log error

```
 type: 'Normal' reason: 'CREATE' ConfigMap kube-ingress/nginx-ingress-nginx-controller
E0608 06:53:29.957636       8 reflector.go:127] k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource
```

**Comment by akranga** [comment]
Suggesting to divorce to the helm chart distribution and change it in favour official from vendor. See [nginx-ingress](https://github.com/agilestacks/kubeflow-components/tree/v1.5.0/nginx-ingress) component

**Comment by TheRealSpaceShip** [comment]
Same for GKE v1.22
